[project]
name = "beat-c-base-org-lektor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flake8>=7.2.0",
    "lektor>=3.3.12",
    "pytest>=8.3.5",
]
