name: 'Lektor deploy to webserver.c-base.org'

on:
  push:
    branches:
      - master

jobs:
  lektor-build:
    name: Build page
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv venv
        uv pip install -e .
    - name: Build with Lektor
      run: |
        uv run lektor build
    - name: Setup SSH Keys and known_hosts and then deploy
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan 217.197.86.179 >> ~/.ssh/known_hosts
        ssh-keyscan webserver.c-base.org >> ~/.ssh/known_hosts
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ secrets.LEKTOR_DEPLOY_PRODUCTION_KEY }}"
        uv run lektor deploy
